version: '3.9'

services:
  ffpp:
    container_name: ffpp
    depends_on:
      - ffpp-db
    image: ffpp:latest
    build:
      context: ../ffpp-latest
      network: host
      dockerfile: ../ffpp-latest/Dockerfile
      args:
        TIMEZONE: Australia/Sydney
        FFPP_DOMAIN: ffpp.example.com
        NGINX_HTTP_PORT: 80
        NGINX_HTTPS_PORT: 443
    volumes:
      - ../shared_persistent_volume:/root/ffpp/persistent
    tmpfs:
      - /root/ffpp/cache
    network_mode: host
    restart: on-failure

  ffpp-db:
    container_name: ffpp-db
    image: ffpp-mariadb:latest
    build:
      context: ../ffpp-mariadb-latest
      network: host
      dockerfile: ../ffpp-mariadb-latest/Dockerfile
      args:
        TIMEZONE: Australia/Sydney
        MARIADB_USER: ffppapiservice
        MARIADB_PASSWORD: wellknownpassword
    volumes:
      - ../shared_persistent_volume/mariadb_data:/var/lib/mysql
    network_mode: host
    restart: on-failure
